### ISSUE TITLE
Unable to save worlds during ReplayMod playback

### ISSUE THREAD

**Issue by VideoGameSmash12** [Avanatiker/WorldTools#4]
When attempting to use the mod to extract world data from ReplayMod recordings during playback, the mod does properly extract the entity and chunk data, but fails to properly save it due to an UninitializedPropertyAccessException related to server info.

```none
[03:26:43] [DefaultDispatcher-worker-2/ERROR]: Uncaught exception in thread "DefaultDispatcher-worker-2"
kotlin.UninitializedPropertyAccessException: lateinit property serverInfo has not been initialized
	at org.waste.of.time.WorldTools.getServerInfo(WorldTools.java:60) ~[WorldTools-fabric-1.0.0.jar:?]
	at org.waste.of.time.WorldTools$dispatchSessionThread$1.invokeSuspend(WorldTools.java:85) ~[WorldTools-fabric-1.0.0.jar:?]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[org_jetbrains_kotlin_kotlin-stdlib-1.9.10-322b6d1b226d3ad5.jar:?]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108) ~[org_jetbrains_kotlinx_kotlinx-coe-jvm-1.7.3-cb5d5a55314c70b3.jar:?]
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115) ~[org_jetbrains_kotlinx_kotlinx-coe-jvm-1.7.3-cb5d5a55314c70b3.jar:?]
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103) ~[org_jetbrains_kotlinx_kotlinx-coe-jvm-1.7.3-cb5d5a55314c70b3.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584) ~[org_jetbrains_kotlinx_kotlinx-coe-jvm-1.7.3-cb5d5a55314c70b3.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793) ~[org_jetbrains_kotlinx_kotlinx-coe-jvm-1.7.3-cb5d5a55314c70b3.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697) ~[org_jetbrains_kotlinx_kotlinx-coe-jvm-1.7.3-cb5d5a55314c70b3.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684) ~[org_jetbrains_kotlinx_kotlinx-coe-jvm-1.7.3-cb5d5a55314c70b3.jar:?]
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException
```

While this would technically be considered a mod conflict, you should consider looking into fixing it nonetheless because it would make it possible to retroactively recover world data from ReplayMod recordings.

**Comment by Avanatiker** [comment]
This is probably fixed in the latest nightly. Please try that and report again if you have any issues. Thanks for reporting!
