### ISSUE TITLE
Running into error with storage containers

### ISSUE THREAD

**Issue by secretbetta** [Avanatiker/WorldTools#9]
I'm getting an error on 1.20.2:
Error: java.lang.NoClassDefFoundError: Could not initialize class org.waste.of.time.storage.StorageManager

Seems like the error happens when chests are attempted to be stored.

Stack trace:
```
java.lang.NoClassDefFoundError: Could not initialize class org.waste.of.time.storage.StorageManager
	at org.waste.of.time.WorldTools.checkCache(WorldTools.java:98)
	at org.waste.of.time.event.Events.onChunkLoad(Events.java:25)
	at net.minecraft.class_631.handler$zle001$worldtools$onChunkLoad(class_631.java:1020)
	at net.minecraft.class_631.method_16020(class_631.java:123)
	at net.minecraft.class_634.method_38539(class_634.java:732)
	at net.minecraft.class_634.method_11128(class_634.java:697)
	at net.minecraft.class_2672.method_11528(class_2672.java:45)
	at net.minecraft.class_2672.method_11054(class_2672.java:12)
	at net.minecraft.class_2600.method_11072(class_2600.java:23)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)
	at net.minecraft.class_1255.method_5383(class_1255.java:115)
	at net.minecraft.class_310.method_1523(class_310.java:1231)
	at net.minecraft.class_310.method_1514(class_310.java:856)
	at net.minecraft.client.main.Main.main(Main.java:253)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoClassDefFoundError: net/minecraft/class_167$class_168 [in thread "DefaultDispatcher-worker-1"]
	at org.waste.of.time.storage.StorageManager.<clinit>(StorageManager.java:57)
	at org.waste.of.time.event.Events$onClientJoin$$inlined$tryWithSession$1.invoke(Events.java:127)
	at org.waste.of.time.event.Events$onClientJoin$$inlined$tryWithSession$1.invoke(Events.java:69)
	at org.waste.of.time.WorldTools$dispatchSessionThread$1.invokeSuspend(WorldTools.java:82)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

**Comment by Avanatiker** [comment]
Thanks for reporting. Please try to reproduce it on the latest nightly because the code base has changed a lot.
